# Generated by Django 3.2.4 on 2021-07-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
